default:
    api:
        twitter:
            consumerkey: CONSUMERKEY
            consumersecret: CONSUMERSECRET
            accestoken: ACCESSTOKEN
            accesstokensecret: ACCESSTOKENSECRET
    db:
        ip: IP
        port: PORT
        db: DB

